window.SMART_CAMEL_DATA = {
  metrics: [
    { key: 'registeredCamels', value: 1248 },
    { key: 'activeFarms', value: 37 },
    { key: 'healthAlerts', value: 12 },
    { key: 'activeAuctions', value: 6 },
    { key: 'connectedSensors', value: 914 },
    { key: 'featureCoverage', value: '90' }
  ],
  camels: [
    { id: 'CAMEL-001', nameAr: 'وضحاء', nameEn: 'Wadha', breedAr: 'مجاهيم', breedEn: 'Majaheem', age: 6, health: 94, activity: 81, farmAr: 'مزرعة الوادي', farmEn: 'Al Wadi Farm' },
    { id: 'CAMEL-014', nameAr: 'شاهين', nameEn: 'Shaheen', breedAr: 'وضح', breedEn: 'Wodh', age: 8, health: 82, activity: 68, farmAr: 'مزرعة الرمال', farmEn: 'Al Rimal Farm' },
    { id: 'CAMEL-027', nameAr: 'هتان', nameEn: 'Hattan', breedAr: 'شعل', breedEn: 'Shael', age: 5, health: 76, activity: 57, farmAr: 'مزرعة السنام', farmEn: 'Al Sanam Farm' },
    { id: 'CAMEL-041', nameAr: 'نوادر', nameEn: 'Nawader', breedAr: 'صفر', breedEn: 'Sufr', age: 7, health: 91, activity: 73, farmAr: 'مزرعة الأصايل', farmEn: 'Al Asayel Farm' }
  ],
  alerts: [
    { level: 'high', titleAr: 'ارتفاع حرارة محتمل', titleEn: 'Potential elevated temperature', textAr: 'CAMEL-027 تجاوز خط الأساس الصحي التجريبي.', textEn: 'CAMEL-027 exceeded the synthetic health baseline.' },
    { level: 'medium', titleAr: 'انخفاض نشاط', titleEn: 'Reduced activity', textAr: 'CAMEL-014 أظهر انخفاضاً في الحركة مقارنة باليوم السابق.', textEn: 'CAMEL-014 shows lower movement than the previous day.' },
    { level: 'low', titleAr: 'اقتراب من سياج جغرافي', titleEn: 'Geofence proximity', textAr: 'قطيع مزرعة الرمال يقترب من حد جغرافي تجريبي.', textEn: 'Al Rimal herd is approaching a demonstration geofence boundary.' }
  ],
  features: [
    ['F001','digitalIdentity','Camel Digital Identity','الهوية الرقمية للإبل','Implemented'],
    ['F002','registry','Camel Registry','السجل الموحد للإبل','Implemented'],
    ['F003','farmOps','Smart Farm Management','إدارة المزارع الذكية','Demonstrated'],
    ['F004','herdOps','Herd Operations','إدارة القطعان','Demonstrated'],
    ['F005','health','Smart Health Intelligence','ذكاء الصحة','Simulated'],
    ['F006','medical','Camel Medical History','السجل الطبي للإبل','Demonstrated'],
    ['F007','sensors','IoT Sensor Center','مركز مستشعرات إنترنت الأشياء','Simulated'],
    ['F008','activity','Camel Activity Intelligence','ذكاء نشاط الإبل','Simulated'],
    ['F009','feeding','Feeding Intelligence','ذكاء التغذية','Simulated'],
    ['F010','training','Training Intelligence','ذكاء التدريب','Simulated'],
    ['F011','grazing','Smart Grazing Intelligence','ذكاء الرعي','Simulated'],
    ['F012','geofence','Geo-Fencing','السياج الجغرافي','Demonstrated'],
    ['F013','highway','Highway Safety','سلامة الطرق','Simulated'],
    ['F014','threats','Predator and Threat Protection','الحماية من المفترسات والمخاطر','Simulated'],
    ['F015','environment','Environmental Risk','المخاطر البيئية','Simulated'],
    ['F016','routes','Migration and Grazing Routes','مسارات التنقل والرعي','Simulated'],
    ['F017','geoDatabase','Geographic Camel Database','قاعدة البيانات الجغرافية للإبل','Demonstrated'],
    ['F018','vision','Artificial Intelligence Vision','الرؤية بالذكاء الاصطناعي','Simulated'],
    ['F019','healthAI','Artificial Intelligence Health Detection','كشف الحالات الصحية بالذكاء الاصطناعي','Simulated'],
    ['F020','recommendation','Artificial Intelligence Recommendation Center','مركز توصيات الذكاء الاصطناعي','Simulated'],
    ['F021','predictive','Predictive Intelligence','الذكاء التنبؤي','Simulated'],
    ['F022','risk','Unified Risk Engine','محرك المخاطر الموحد','Simulated'],
    ['F023','lineage','Genetics and Lineage','الجينات والأنساب','Demonstrated'],
    ['F024','breeding','Breeding Intelligence','ذكاء التكاثر','Simulated'],
    ['F025','dna','DNA Evidence Registry','سجل أدلة الحمض النووي','Planned'],
    ['F026','mazayen','Mazayen Management','إدارة المزايين','Demonstrated'],
    ['F027','beautyAI','Artificial Intelligence Beauty Evaluation','تقييم الجمال بالذكاء الاصطناعي','Simulated'],
    ['F028','manipulation','Manipulation Detection','كشف التلاعب','Simulated'],
    ['F029','racing','Camel Racing','سباقات الإبل','Demonstrated'],
    ['F030','endurance','Endurance Competitions','مسابقات التحمل','Demonstrated'],
    ['F031','milkCompetition','Milk Competitions','مسابقات الحليب','Demonstrated'],
    ['F032','festival','Festival Management','إدارة المهرجانات','Demonstrated'],
    ['F033','calendar','Festival Calendar','تقويم المهرجانات','Implemented'],
    ['F034','auctions','Camel Auctions','مزادات الإبل','Demonstrated'],
    ['F035','qualification','Auction Qualification Engine','محرك تأهيل المزادات','Simulated'],
    ['F036','valuation','Market Valuation','التقييم السوقي','Simulated'],
    ['F037','marketplace','Digital Marketplace','السوق الرقمي','Demonstrated'],
    ['F038','negotiation','Negotiation Workflow','مسار التفاوض','Demonstrated'],
    ['F039','ownership','Ownership History','سجل الملكية','Implemented'],
    ['F040','certificate','Trusted Digital Certificate','الشهادة الرقمية الموثوقة','Demonstrated'],
    ['F041','qr','Quick Response Verification','التحقق عبر رمز الاستجابة السريعة','Demonstrated'],
    ['F042','milk','Milk Production','إنتاج الحليب','Demonstrated'],
    ['F043','meat','Meat Production','إنتاج اللحوم','Planned'],
    ['F044','quality','Product Quality Intelligence','ذكاء جودة المنتجات','Simulated'],
    ['F045','products','Camel Products Marketplace','سوق منتجات الإبل','Planned'],
    ['F046','supplyDemand','Supply and Demand Analytics','تحليلات العرض والطلب','Simulated'],
    ['F047','farmAuction','Farm Auction','مزادات المزارع','Planned'],
    ['F048','farmMarket','Farm Marketplace','سوق المزارع','Planned'],
    ['F049','analytics','Performance Analytics','تحليلات الأداء','Implemented'],
    ['F050','bigData','Big Data Analytics','تحليلات البيانات الكبيرة','Demonstrated'],
    ['F051','threeD','Three-Dimensional Profile','الملف ثلاثي الأبعاد','Planned'],
    ['F052','sustainability','Sustainability Analytics','تحليلات الاستدامة','Simulated'],
    ['F053','smartEnvironment','Smart Environment Integration','التكامل مع البيئة الذكية','Mock Integration'],
    ['F054','government','Government Integration Layer','طبقة التكامل الحكومي','Mock Integration'],
    ['F055','compliance','Regulatory and Compliance Layer','طبقة الامتثال والتنظيم','Demonstrated'],
    ['F056','global','Globalization Layer','طبقة التوسع العالمي','Demonstrated'],
    ['F057','tourism','Tourism Layer','الطبقة السياحية','Planned'],
    ['F058','heritage','Heritage and Culture','التراث والثقافة','Implemented'],
    ['F059','education','Camel Anatomy and Education','تشريح الإبل والتعليم','Implemented'],
    ['F060','audit','Evidence and Audit Log','سجل الأدلة والتدقيق','Implemented'],
    ['F061','wellbeing','Camel Psychological State Assessment','تقييم الحالة النفسية للإبل','Simulated'],
    ['F062','interactiveGrazing','Interactive Smart Grazing Management','إدارة الرعي الذكي التفاعلية','Simulated'],
    ['F063','audioDeterrence','Directed Audio Stimulation','التحفيز الصوتي الموجّه','Simulated'],
    ['F064','lightWarning','Directed Light Warning System','نظام التحذير الضوئي الموجّه','Simulated'],
    ['F065','ultrasoundEscape','Ultrasound and Infrasound Highway Escape System','نظام الإبعاد بالموجات فوق وتحت الصوتية عن الطرق','Simulated'],
    ['F066','waveProtection','Wave and Vibration Predator Deterrence','الحماية من المفترسات بالموجات والاهتزازات','Simulated'],
    ['F067','competitionPerformance','Artificial Intelligence Competition Performance Analysis','تحليل أداء المسابقات بالذكاء الاصطناعي','Simulated'],
    ['F068','breedBeauty','Breed-Specific Beauty Evaluation','تقييم الجمال حسب السلالة','Simulated'],
    ['F069','localGlobalBeauty','Local and International Beauty Standards','معايير الجمال المحلية والدولية','Demonstrated'],
    ['F070','spectralInspection','Spectral and Ultrasound Manipulation Inspection','الفحص الطيفي وبالموجات فوق الصوتية لكشف التلاعب','Simulated'],
    ['F071','audienceJudging','Interactive Audience Evaluation','التقييم التفاعلي للجمهور','Demonstrated'],
    ['F072','blockchainEvidence','Blockchain Evidence Documentation','توثيق الأدلة باستخدام البلوك تشين','Planned'],
    ['F073','auctionStreaming','Live Auction Streaming','البث المباشر للمزادات','Planned'],
    ['F074','auction3D','Three-Dimensional Auction Viewing','العرض ثلاثي الأبعاد في المزادات','Planned'],
    ['F075','delivery','Camel Delivery and Logistics','خدمات توصيل ونقل الإبل','Planned'],
    ['F076','medicineMarket','Camel Medicines and Supplements Section','قسم أدوية ومكملات الإبل','Planned'],
    ['F077','foodDirectory','Camel Foods and Restaurants Directory','دليل أطعمة ومطاعم منتجات الإبل','Planned'],
    ['F078','reviews','Product and Restaurant Reviews and Ratings','تقييمات ومراجعات المنتجات والمطاعم','Planned'],
    ['F079','globalFestivals','Global Festival Coordination','التنسيق العالمي للمهرجانات','Mock Integration'],
    ['F080','multilingualReports','Multilingual Festival Reporting','تقارير المهرجانات متعددة اللغات','Demonstrated'],
    ['F081','environmentRefresh','Automatic Daily Environmental Data Refresh','التحديث اليومي التلقائي للبيانات البيئية','Mock Integration'],
    ['F082','jointEnvironmentReports','Joint Smart Environment Reports','التقارير المشتركة مع منصة البيئة الذكية','Mock Integration'],
    ['F083','supplyChain','Production Supply Chain Traceability','تتبع سلسلة توريد الإنتاج','Planned'],
    ['F084','costAnalytics','Production Cost Analytics','تحليلات تكاليف الإنتاج','Simulated'],
    ['F085','researchRepository','Global Camel Research Data Repository','مستودع عالمي لبيانات أبحاث الإبل','Planned'],
    ['F086','seasonalUpdates','Seasonal Environment and Nutrition Updates','التحديثات الموسمية للبيئة والتغذية','Mock Integration'],
    ['F087','virtualExperience','Virtual-Reality Market Experience','تجربة السوق بالواقع الافتراضي','Planned'],
    ['F088','qualityCertificates','Product Quality Certificates','شهادات جودة منتجات الإبل','Demonstrated'],
    ['F089','globalProductMarkets','Local and International Product Market Integration','تكامل منتجات الإبل مع الأسواق المحلية والعالمية','Mock Integration'],
    ['F090','environmentalWellbeing','Camel Environmental Wellbeing Management','إدارة الرفاه البيئي للإبل','Simulated']
  ].map(function (f) {
    return { id:f[0], domain:f[1], nameEn:f[2], nameAr:f[3], status:f[4] };
  })
};
